# Generated by Django 4.2.5 on 2023-09-07 15:47

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[finance.models.upper_case])),
            ],
        ),
    ]
