# Generated by Django 4.2.5 on 2023-09-07 16:11

from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_stock_stockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_start_date', models.DateField(blank=True, default=None, null=True)),
                ('request_end_date', models.DateField(blank=True, default=None, null=True)),
                ('process_start_date', models.DateField(blank=True, default=None, null=True)),
                ('gross_end_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[finance.models.upper_case])),
            ],
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='initial_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='purchase_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='date_flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.dateflowmodel'),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.saleservicemodel'),
        ),
    ]
