# Generated by Django 4.2.5 on 2023-09-08 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_dateflowmodel_saleservicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='stockmodel',
            name='process',
        ),
        migrations.RemoveField(
            model_name='stockmodel',
            name='purchase_quantity',
        ),
        migrations.CreateModel(
            name='StockOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.FloatField(default=0.0)),
                ('purchase_quantity', models.IntegerField(default=0)),
                ('process', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.stockmodel')),
            ],
        ),
    ]
