# Generated by Django 4.2.5 on 2023-09-08 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_remove_stockmodel_initial_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockOwner',
            new_name='StockOwnerModel',
        ),
    ]
