# Generated by Django 4.2.5 on 2023-09-08 04:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapermodel',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scrapermodel',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
